server:
  port: 10000
eureka:
  instance:
    hostname: dev
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: true
    peer-eureka-nodes-update-interval-ms: 10000
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defalutZone: http://localhost:10000/eureka/
spring:
  application:
    name: eureka-peer1